### ISSUE TITLE
Julia-repl would not start on Windows

### ISSUE THREAD

**Issue by PetrKryslUCSD** [tpapp/julia-repl#89] opened 2020-06-15 21:53 UTC
This is what I get when running M-x julia-repl:
Warning (emacs): could not capture basedir for Julia executable julia

Windows 10, Emacs 26.3

**Comment by PetrKryslUCSD** [comment] 2020-06-16 00:07
Sorry, I forgot that this was already covered: https://github.com/tpapp/julia-repl/issues/20

**Comment by apparluk** [comment] 2020-08-02 23:53
@PetrKryslUCSD Since the merging of https://github.com/tpapp/julia-repl/commit/dddc6fd68a26ad3fb706cf59b4d63599a6be6da1 on 22 Jun 2020 does the warning still appear?

**Comment by PetrKryslUCSD** [comment] 2020-08-03 00:35
I couldn't get the terminal to work well on Windows, and I'm afraid I gave up on it some time ago. Sorry. I think you can close this issue.

**Comment by apparluk** [comment] 2020-08-03 06:16
> couldn't get the terminal to work well

What about [fakecygpty](https://github.com/d5884/fakecygpty)?

**Comment by tpapp** [comment] 2020-08-03 12:24
Thanks, closing. If the issue is still relevant please just open a new one.

**Closed** 2021-01-14 15:50 UTC
